### ISSUE TITLE
Error using --polar

### ISSUE THREAD

**Issue by Gadgeteering** [CGrassin/acoustic_beamforming#1]
Code_Pattern/beamforming_pattern_gen.py", line 97, in plot_pattern
    ax.plot(math.radians(theta), mag)
TypeError: only size-1 arrays can be converted to Python scalars

Fixed by changing

`ax.plot(math.radians(theta), mag)`

to

`ax.plot(np.radians(theta), mag)`

**Comment by CGrassin** [comment]
Thank you for the report! Fixed in commit https://github.com/CGrassin/acoustic_beamforming/commit/aa21987e1556db3a379716d3c3026c5e7df7526d .
